### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by fishfree** [jaluoma/pruju-ai#2]
A great workpiece!

```
(prujuai) mememe@ubuntugpu:~/prujuai$ vi .moodle
(prujuai) mememe@ubuntugpu:~/prujuai$ python moodle.py 
Traceback (most recent call last):
  File "/mnt/data/mememe/prujuai/moodle.py", line 144, in <module>
    df=ws_create_file_list(resp)
  File "/mnt/data/mememe/prujuai/moodle.py", line 107, in ws_create_file_list
    for module in section.get('modules', []):
AttributeError: 'str' object has no attribute 'get'
```

BTW: What's the exact python version of your working instance? @jaluoma  Thank you very much!

**Comment by jaluoma** [comment]
This is probably due to an access issue on the Moodle end. I was able to replicate this by providing a wrong access token in .moodle. I admit the error message is not very helpful in this regard (i.e., thanks for the useful issue!).

**Comment by jaluoma** [comment]
re: Python version: At least 3.10 and 3.11 work.

**Comment by fishfree** [comment]
Thank you, jaluoma!
I can confirm my token is correct. Maybe it's because of the token-associated user has not enough permissions. Could you write it clearly here or in the README, please?

**Comment by jaluoma** [comment]
Thanks! The documentation sure needs to be better. :)
