### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443)

### ISSUE THREAD

**Issue by fishfree** [jaluoma/pruju-ai#3]
This error is caused by my networking. But I explicitly set `LLM_PROVIDER="openai"` and `MODEL_NAME="gpt-4"` in .env file. Why does it still request from Azure API?

**Comment by jaluoma** [comment]
Strange. I am unable to reproduce this. This works for me:

```
LLM_PROVIDER="openai"
MODEL_NAME="gpt-4"
OPENAI_API_KEY="secret-key"
```

**Comment by fishfree** [comment]
Now it works as expected. I don't why. Let it go.
